enyo.depends(
	"stylesheets/app.css",
	"source/Util.js",
	"source/Inflate.js",
	"source/Wmf.js",
	"source/ShapeTable.js",
	"source/Shapes.js",
	"source/PresetTable.js",
	"source/Drawing.js",
	"source/Docx.js",
	"source/Doc.js",
	"source/Browser.js",
	"source/DocView.js",
	"source/App.js"
);
