// Makes app/source/PresetTable.js from LibreOffice's definitions of the preset shapes
// of the newer Office formats (.docx, .xlsx, .pptx).
//   node tools/gen-presets.js <libreoffice-core checkout> [out file]
// It reads oox/source/drawingml/customshapes/presetShapeDefinitions.xml from that
// checkout. The data written is LibreOffice's, under the Mozilla Public License 2.0;
// this script only changes its form.
var fs = require("fs");
var path = require("path");

var core = process.argv[2];
var out = process.argv[3] || path.join(__dirname, "..", "app", "source", "PresetTable.js");
if (!core) {
	console.log("usage: node gen-presets.js <libreoffice-core checkout> [out file]");
	process.exit(1);
}
var xml = fs.readFileSync(path.join(core, "oox/source/drawingml/customshapes/presetShapeDefinitions.xml"), "utf8");
xml = xml.replace(/<!--[\s\S]*?-->/g, "");

function attrs(text) {
	var a = {};
	var re = /([\w:]+)\s*=\s*"([^"]*)"/g;
	var m;
	while ((m = re.exec(text))) {
		a[m[1]] = m[2];
	}
	return a;
}
// A number where it is one, else the name of a guide.
function value(v) {
	return /^-?\d+$/.test(v) ? parseInt(v, 10) : v;
}
function inner(text, tag) {
	var m = new RegExp("<" + tag + "\\b[^>]*?(?:/>|>([\\s\\S]*?)</" + tag + ">)").exec(text);
	return m ? (m[1] || "") : null;
}
function guides(text) {
	var list = [];
	var re = /<gd\b([^>]*)>/g;
	var m;
	while ((m = re.exec(text || ""))) {
		var a = attrs(m[1]);
		list.push(a.name, a.fmla);
	}
	return list;
}

var shapes = {};
var count = 0;
var top = /<(\w+)>\s*\n([\s\S]*?)\n\s*<\/\1>/g;
var body = xml.substring(xml.indexOf("<presetShapeDefinitons>") + 23);
var m;
while ((m = top.exec(body))) {
	var name = m[1];
	var text = m[2];
	var shape = {};
	var av = guides(inner(text, "avLst"));
	var gd = guides(inner(text, "gdLst"));
	if (av.length) { shape.av = av; }
	if (gd.length) { shape.gd = gd; }
	var rect = /<rect\b([^>]*)>/.exec(text);
	if (rect) {
		var r = attrs(rect[1]);
		shape.rect = [value(r.l), value(r.t), value(r.r), value(r.b)];
	}
	shape.paths = [];
	var pathRe = /<path\b([^>]*?)(?:\/>|>([\s\S]*?)<\/path>)/g;
	var list = inner(text, "pathLst") || "";
	var p;
	while ((p = pathRe.exec(list))) {
		var pa = attrs(p[1]);
		var one = {c: []};
		if (pa.w) { one.w = parseInt(pa.w, 10); }
		if (pa.h) { one.h = parseInt(pa.h, 10); }
		if (pa.fill && pa.fill !== "norm") { one.fill = pa.fill; }
		if (pa.stroke === "false" || pa.stroke === "0") { one.stroke = false; }
		// Commands, flat: a letter, then its numbers or guide names.
		//   M x y, L x y, A wR hR stAng swAng, C x1 y1 x2 y2 x y, Q x1 y1 x y, Z
		var cmdRe = /<(moveTo|lnTo|arcTo|cubicBezTo|quadBezTo|close)\b([^>]*?)(?:\/>|>([\s\S]*?)<\/\1>)/g;
		var c;
		while ((c = cmdRe.exec(p[2] || ""))) {
			if (c[1] === "close") {
				one.c.push("Z");
			} else if (c[1] === "arcTo") {
				var aa = attrs(c[2]);
				one.c.push("A", value(aa.wR), value(aa.hR), value(aa.stAng), value(aa.swAng));
			} else {
				one.c.push({moveTo: "M", lnTo: "L", cubicBezTo: "C", quadBezTo: "Q"}[c[1]]);
				var ptRe = /<pt\b([^>]*)>/g;
				var pt;
				while ((pt = ptRe.exec(c[3] || ""))) {
					var pp = attrs(pt[1]);
					one.c.push(value(pp.x), value(pp.y));
				}
			}
		}
		shape.paths.push(one);
	}
	shapes[name] = shape;
	count++;
}

var lines = [
	"/* -*- Mode: JavaScript; tab-width: 4 -*- */",
	"/*",
	" * This file is part of Papers and is derived from the LibreOffice project.",
	" *",
	" * This Source Code Form is subject to the terms of the Mozilla Public",
	" * License, v. 2.0. If a copy of the MPL was not distributed with this",
	" * file, You can obtain one at http://mozilla.org/MPL/2.0/.",
	" */",
	"",
	"// GENERATED by tools/gen-presets.js. Do not edit; change the generator and run it again.",
	"//",
	"// The preset shapes of the newer Office formats (a:prstGeom in .docx, .xlsx, .pptx),",
	"// taken from LibreOffice: oox/source/drawingml/customshapes/presetShapeDefinitions.xml",
	"// PP.Drawing (Drawing.js) works them out and draws them.",
	"//",
	"// By the shape's name in the file format:",
	"//   av    its adjust values and their defaults, as name, formula, name, formula...",
	"//   gd    its guides (named formulas), the same way",
	"//   rect  where text goes: left, top, right, bottom (numbers or guide names)",
	"//   paths each {c: commands, w, h: the grid its points are on if not the shape's size,",
	"//         fill: \"none\", \"lighten\", \"darken\"... if not plain, stroke: false if not outlined}",
	"//         commands: M x y, L x y, A wR hR stAng swAng, C x1 y1 x2 y2 x y, Q x1 y1 x y, Z",
	"",
	"PP.PresetTable = {"
];
var keys = Object.keys(shapes).sort();
keys.forEach(function(k, i) {
	lines.push("\t" + k + ": " + JSON.stringify(shapes[k]).replace(/"(av|gd|rect|paths|c|w|h|fill|stroke)":/g, "$1:") + (i < keys.length - 1 ? "," : ""));
});
lines.push("};");
lines.push("");
fs.writeFileSync(out, lines.join("\n"));
console.log(count + " shapes; wrote " + fs.statSync(out).size + " bytes to " + out);
